### ISSUE TITLE
Document full URI spec

### ISSUE THREAD

**Issue by fulldecent** [ipfs/specs#307] opened 2022-08-09 02:27 UTC
Please fully document the URI specification for IPFS (and maybe IPNS if in scope).

This should also fully specify how to interpret this URI

> https://ipfs.io/ipfs/bafybeia5f2yk6td7ciroeped2uwfivo333b524t3zmoderfhl3xn7wi7aa/&sa=D&source=editors&ust=1651157762663308&usg=AOvVaw1sQEgWa5q7YI8HnLTPUq0Y

which is referenced by the IPFS documentation at https://github.com/ipfs/ipfs-docs/blob/6467bdb5df6ba5188f6d415c183ccb138b150cf1/docs/how-to/create-simple-chat-app.md

**Comment by lidel** [comment] 2022-09-01 19:28
@fulldecent  that URI does not appear in the page you linked.
Either way, this is duplicate of #138 , let's continue there.

**Closed by lidel** 2022-09-01 19:28 UTC
Labels: need/triage

**Comment by fulldecent** [comment] 2022-09-01 20:11
Issue 138 addresses ipfs:// URLs, this issue addresses https://ipfs.io/ipfs/ URLs. I guess these are related.

I'll bring this up in the other issue.
